server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
      label: master
        git:
          uri: https://github.com/huangcong9588/spring-could-config.git
          username: huangcong9588
          password: hc788824
#          search-paths: respo
name: huangcong-sprng-could-config-name