server:
  port: 8765
spring:
  application:
    name: service-hi
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
#security:
#  user:
#    name: admin
#    password: admin
#  basic:
#    enabled: false
