server:
  port: 8765
spring:
  application:
    name: service-hi
  #数据源
  datasource:
    url: jdbc:mysql://192.169.1.211:3306/db_paws_main?characterEncoding=utf-8&allowMultiQueries=true
    username: test
    password: test  
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
name: huangcong-config测试第三次修改
#security:
#  user:
#    name: admin
#    password: admin
#  basic:
#    enabled: false
#公共固定配置
mybatis:
   config-location: classpath:mybatis.xml

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
